[package]
name = "alsa"
version = "0.0.1"
authors = ["David Henningsson <diwic@ubuntu.com>"]

description = "Thin but safe wrappers for ALSA (Advanced Linux Sound Architecture)"
repository = "https://github.com/diwic/alsa-rs"
# documentation = "http://diwic.github.io/alsa-rs-docs/alsa"
keywords = ["ALSA", "audio", "sound"]
license = "Apache-2.0/MIT"

[dependencies]
libc = "*"
alsa-sys = "*"
